<?php

/**
 * @file
 * OCHA locations logic.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\ocha_locations\Controller\OchaLocationsController;

/**
 * Returns a controller.
 */
function ocha_locations_get_controller() {
  return new OchaLocationsController(
    \Drupal::service('http_client'),
    \Drupal::service('config.factory'),
    \Drupal::service('cache.ocha_locations'),
    \Drupal::service('logger.factory'),
    \Drupal::service('state'),
    \Drupal::service('file_system')
  );
}

/**
 * Allowed values callback.
 *
 * @param \Drupal\field\Entity\FieldStorageConfig $definition
 *   The field definition.
 * @param \Drupal\Core\Entity\ContentEntityInterface|null $entity
 *   The entity being created if applicable.
 * @param bool $cacheable
 *   Boolean indicating if the results are cacheable.
 *
 * @return array
 *   An array of possible key and value options.
 *
 * @see options_allowed_values()
 */
function ocha_locations_allowed_values_function(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  $controller = ocha_locations_get_controller();
  return $controller->getAllowedValues();
}

/**
 * Allowed values callback.
 */
function ocha_locations_allowed_values_by_parent($parent = 0, $grand_parent = 0) {
  $controller = ocha_locations_get_controller();
  return $controller->getAllowedValuesByParent($parent, $grand_parent);
}

/**
 * Convert children to options.
 */
function ocha_locations_children_to_options($location) {
  $controller = ocha_locations_get_controller();
  return $controller->getChildrenAsOptions($location);
}

/**
 * Get one item().
 */
function ocha_locations_get_item($id, $langcode = NULL) {
  $controller = ocha_locations_get_controller();
  return $controller->getItem($id);
}

/**
 * Implements hook_cron().
 */
function ocha_locations_cron() {
  $controller = ocha_locations_get_controller();
  $controller->getApiData(TRUE);
}

/**
 * Load from JSON.
 */
function ocha_locations_import_json() {
  $controller = ocha_locations_get_controller();
  $controller->getApiDataFromJson();
}
