<?php

/**
 * @file
 * OCHA locations logic.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\ocha_locations\Controller\OchaLocationsController;

/**
 * Returns a controller.
 */
function ocha_locations_get_controller() {
  return new OchaLocationsController(
    \Drupal::service('http_client'),
    \Drupal::service('config.factory'),
    \Drupal::service('cache.ocha_locations'),
    \Drupal::service('logger.factory'),
    \Drupal::service('state'),
    \Drupal::service('file_system')
  );
}

/**
 * Allowed values callback.
 *
 * @param \Drupal\field\Entity\FieldStorageConfig $definition
 *   The field definition.
 * @param \Drupal\Core\Entity\ContentEntityInterface|null $entity
 *   The entity being created if applicable.
 * @param bool $cacheable
 *   Boolean indicating if the results are cacheable.
 *
 * @return array
 *   An array of possible key and value options.
 *
 * @see options_allowed_values()
 */
function ocha_locations_allowed_values_function(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  return ocha_locations_allowed_values();
}

/**
 * Allowed values callback.
 */
function ocha_locations_allowed_values() {
  static $options;

  if (isset($options)) {
    return $options;
  }

  $controller = ocha_locations_get_controller();
  $options = $controller->getAllowedValues();

  return $options;
}

/**
 * Allowed top level values callback.
 */
function ocha_locations_allowed_values_top_level() {
  static $options;

  if (isset($options)) {
    return $options;
  }

  $controller = ocha_locations_get_controller();
  $options = $controller->getAllowedValuesTopLevel();

  return $options;
}

/**
 * Convert children to options.
 */
function ocha_locations_children_to_options($location) {
  $controller = ocha_locations_get_controller();
  return $controller->getChildrenAsOptions($location);
}

/**
 * Get one item by Id.
 */
function ocha_locations_get_item($id, $langcode = NULL) {
  static $items;

  if (isset($items) && isset($items[$id])) {
    return $items[$id];
  }

  $controller = ocha_locations_get_controller();
  $items[$id] = $controller->getItem($id);

  return $items[$id];
}

/**
 * Get one item by label.
 */
function ocha_locations_get_item_by_label($label) {
  $options = ocha_locations_allowed_values();

  if ($index = array_search($label, $options)) {
    return ocha_locations_get_item($index);
  }

  return FALSE;
}

/**
 * Implements hook_cron().
 */
function ocha_locations_cron() {
  $controller = ocha_locations_get_controller();
  $controller->getApiData(TRUE);
}

/**
 * Load from JSON.
 */
function ocha_locations_import_json() {
  $controller = ocha_locations_get_controller();
  $controller->getApiDataFromJson();
}
