<?php

/**
 * @file
 * OCHA disasters logic.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\ocha_disasters\Controller\OchaDisastersController;

/**
 * Returns a controller.
 */
function ocha_disasters_get_controller() {
  return new OchaDisastersController(
    \Drupal::service('http_client'),
    \Drupal::service('config.factory'),
    \Drupal::service('cache.ocha_disasters'),
    \Drupal::service('logger.factory'),
    \Drupal::service('state'),
    \Drupal::service('file_system')
  );
}

/**
 * Allowed values callback.
 *
 * @param \Drupal\field\Entity\FieldStorageConfig $definition
 *   The field definition.
 * @param \Drupal\Core\Entity\ContentEntityInterface|null $entity
 *   The entity being created if applicable.
 * @param bool $cacheable
 *   Boolean indicating if the results are cacheable.
 *
 * @return array
 *   An array of possible key and value options.
 *
 * @see options_allowed_values()
 */
function ocha_disasters_allowed_values_function(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  static $options;

  if (isset($options)) {
    return $options;
  }

  $controller = ocha_disasters_get_controller();
  $options = $controller->getAllowedValues();

  return $options;
}

/**
 * Get one item.
 */
function ocha_disasters_get_item($id, $langcode = NULL) {
  $controller = ocha_disasters_get_controller();

  return $controller->getItem($id);
}

/**
 * Get one item by glide.
 */
function ocha_disasters_get_item_by_glide($glide) {
  $controller = ocha_disasters_get_controller();

  return $controller->getItemByGlide($glide);
}

/**
 * Implements hook_cron().
 */
function ocha_disasters_cron() {
  $controller = ocha_disasters_get_controller();

  // Populate cache.
  $controller->getApiData(TRUE);
}

/**
 * Load from JSON.
 */
function ocha_disasters_import_json() {
  $controller = ocha_disasters_get_controller();
  $controller->getApiDataFromJson();
}
