<?php

/**
 * @file
 * OCHA organizations logic.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\ocha_organizations\Controller\OchaOrganizationsController;

/**
 * Returns a controller.
 */
function ocha_organizations_get_controller() {
  return new OchaOrganizationsController(
    \Drupal::service('http_client'),
    \Drupal::service('config.factory'),
    \Drupal::service('cache.ocha_organizations'),
    \Drupal::service('logger.factory'),
    \Drupal::service('state'),
    \Drupal::service('file_system')
  );
}

/**
 * Allowed values callback.
 *
 * @param \Drupal\field\Entity\FieldStorageConfig $definition
 *   The field definition.
 * @param \Drupal\Core\Entity\ContentEntityInterface|null $entity
 *   The entity being created if applicable.
 * @param bool $cacheable
 *   Boolean indicating if the results are cacheable.
 *
 * @return array
 *   An array of possible key and value options.
 *
 * @see options_allowed_values()
 */
function ocha_organizations_allowed_values_function(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  static $options;

  if (isset($options)) {
    return $options;
  }

  $controller = ocha_organizations_get_controller();
  $options = $controller->getAllowedValues();

  return $options;
}

/**
 * Get one item().
 */
function ocha_organizations_get_item($id, $langcode = NULL) {
  $controller = ocha_organizations_get_controller();
  return $controller->getItem($id);
}

/**
 * Implements hook_cron().
 */
function ocha_organizations_cron() {
  $controller = ocha_organizations_get_controller();
  $controller->getApiData(TRUE);
}

/**
 * Load from JSON.
 */
function ocha_organizations_import_json() {
  $controller = ocha_organizations_get_controller();
  $controller->getApiDataFromJson();
}
