<?php

/**
 * @file
 * Contains custom_widgets.module.
 */

use Drupal\Component\Utility\Crypt;
use Drupal\Core\Site\Settings;

/**
 * Get allowed values from a field.
 */
function custom_widgets_get_allowed_options($entity_type_id, $field_name) {
  $entityManager = \Drupal::service('entity_field.manager');
  $fields = $entityManager->getFieldStorageDefinitions($entity_type_id);
  return options_allowed_values($fields[$field_name]);
}

/**
 * Is select2 available.
 */
function custom_widgets_select2_available() {
  return \Drupal::moduleHandler()->moduleExists('select2');
}

/**
 * Get uid from current user.
 */
function custom_widgets_current_user_uid() {
  return \Drupal::currentUser()->id();
}

/**
 * Calculate a hash.
 */
function custom_widgets_calculate_hash($params) {
  if (isset($params['hash'])) {
    unset($params['hash']);
  }

  return Crypt::hmacBase64(serialize($params), Settings::getHashSalt());
}
